### ISSUE TITLE
Gutter for childs

### ISSUE THREAD

**Issue by vanniktech** [blazsolar/FlowLayout#17]
Is there any way to set the gutter for the Flowlayout? Every child view could then have a margin / padding of 10dp and it'd make styling easier.

**Comment by blazsolar** [comment]
No, at the moment there is no such option. I will look into it and add it if it will make sense.

**Comment by vanniktech** [comment]
@blazsolar any progress on this one?

**Comment by blazsolar** [comment]
Will try to look into it in coming weeks

**Comment by vanniktech** [comment]
Personally I'm no longer interested in this and hence closing it. Thanks anyways :)
