### ISSUE TITLE
Item show with animation

### ISSUE THREAD

**Issue by niteshkhatri** [blazsolar/FlowLayout#23]
Hi. First of all I would like to thank you such a great piece of code. Its really useful.

I have a concern. I want to show the children/items of FlowLayout with animation. All the items should not animate together instead they should animate one by one in the order of their position. I want to apply scale animation on items.

How can I achieve this? Please help me out

Refer this video for reference. 
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B08MbvYZK1iNTGRLb2Zud2RUNFE/animation-meaningfultransitions-hierarchicaltiming-4do_large_xhdpi.webm

**Comment by blazsolar** [comment]
You should just iterate through all the children and add scale animation to every one of them with specified delay.
