### ISSUE TITLE
Add FlowLayout from code

### ISSUE THREAD

**Issue by mohgh** [blazsolar/FlowLayout#9]
I want to add some features to FlowLayout so I create a custom class and extends it from FlowLayout. then I need to instantiate it and add it to FrameLayout with addView. Is this possible or I should only use xml? I tried and nothing appeared in my screen. Thanks in advanced.

**Comment by blazsolar** [comment]
@mohgh This should work as expected. If you see example app provided in this repo you will see example where app is adding and removing views.
